messages:
  reload: "&8[&3&lTotalAfterworld&8] &ahas been reloaded."
  args-error: "&cВведено неверное количество аргументов"
  only-player: "&cКоманда может быть введена только игроком"
  setpoint: "&aТочка установлена"
  death: "&dТы попал в иной мир! Путь обратно тебе укажет проводник. (&eСледуй за белым облаком&d)."
  too-close: "&8[&3&lПроводник&8]: &fЯ не могу подходить к порталу слишком близко. Так что дальше тебе придется идти одному."

debug: false
requirements:
  1:
    type: '>='
    input: '%clv_player_level%'
    output: 5

decrease-time: 1209600 #2 weeks
afterworld: afterworld
default-reincarnation-point: world,-142.5,73,172.5,180,0

enabled-worlds:
  - world

portal:
  minX: -10000
  minZ: -10000
  maxX: 10000
  maxZ: 10000
  
spawns: #min-death: radius
  1: 100
  2: 144
  3: 213
  4: 300
  5: 402
  6: 514
  7: 637
  8: 768
  9: 906
  10: 1052
  11: 1203
  12: 1359
  13: 1521
  14: 1687
  15: 1858
  16: 2032
  17: 2211
  18: 2393
  19: 2578
  20: 2767